DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
  id SERIAL,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id SERIAL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  image VARCHAR(255),
  timestamp TIMESTAMP DEFAULT current_timestamp
);

DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews (
  id SERIAL,
  user_id VARCHAR(255) NOT NULL,
  album_id VARCHAR(255) NOT NULL,
  review VARCHAR(255) NOT NULL
);